### ISSUE TITLE
Error in creation

### ISSUE THREAD

**Issue by anandgeorge** [iotFab/iota-aws-full-node#14]
CREATE_FAILED	AWS::EC2::Instance	Ec2Instance	The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.

**Comment by iotFab** [comment]
What was filled in InstanceTypeParameter?

**Comment by anandgeorge** [comment]
I clicked on the Launch Instance button [here](https://github.com/SemkoDev/nelson.cli#amazon-cloudformation), accepted defaults and created.

**Comment by iotFab** [comment]
Do you have a default-VPC in the region you deploy the cloudformation tempalte? 
If you have an old AWS Account they are not deployed by default.
To create it you can follow the documentation here : 
https://aws.amazon.com/about-aws/whats-new/2017/07/create-a-new-default-vpc-using-aws-console-or-cli/

If this is still not working, could you check with AWS support to figure out the root cause ?

**Comment by anandgeorge** [comment]
Thanks. The default-VPC wasn't setup. It's running now. Small typo [here](https://github.com/iotFab/iota-aws-full-node#step-2-deploy-the-template) ParameterKey=KeyNameParameter

**Comment by iotFab** [comment]
Thank you !
