### ISSUE TITLE
S3 bucket created

### ISSUE THREAD

**Issue by anandgeorge** [iotFab/iota-aws-full-node#15]
One day after setting up the full node, I noticed that a new S3 bucket has been created by the same user account that created the CloudFormation. 

I haven't manually created this bucket. It's named cf-templates-1pukote766dkc-ap-southeast-1.

I don't see it in the CloudFormation resources. Could it have been created by scripts running at startup/ created by AWS automatically to store cf-templates?

The bucket is currently empty

**Comment by iotFab** [comment]
"The CloudFormation console creates a bucket in your account so that when you upload a template from a file through the stack creation and update wizard.

You should not use this bucket for other purposes since the content is managed and potentially cleaned up when you use the console. If your application needs a bucket, you should create a bucket specifically for that use in your template."
https://forums.aws.amazon.com/thread.jspa?threadID=100206

**Comment by anandgeorge** [comment]
Thanks. Another issue I came across installing an instance today was that java would not install because of an issue with the webupd8team ppa. Resolution details are discussed [here](https://ubuntuforums.org/showthread.php?t=2374686&page=4&p=13731177#post13731177)

**Comment by iotFab** [comment]
I will update the script this week to take in account IRI release as well. 
Thank you for reporting this.
